CREATE TABLE [dbo].[mc_groups] (
    [Group_ID]          INT              IDENTITY (956, 1) NOT NULL,
    [Group_Name]        NVARCHAR (255)   CONSTRAINT [DF_mc_groups_Group_Name] DEFAULT (N'') NOT NULL,
    [parent_group_id]   INT              CONSTRAINT [DF_mc_groups_parent_group_id] DEFAULT ('0') NOT NULL,
    [Status]            NVARCHAR (50)    CONSTRAINT [DF_mc_groups_Status] DEFAULT (N'') NULL,
    [Description]       NVARCHAR (MAX)   NULL,
    [link]              NVARCHAR (75)    CONSTRAINT [DF_mc_groups_link] DEFAULT (N'') NULL,
    [forum]             NVARCHAR (50)    CONSTRAINT [DF_mc_groups_forum] DEFAULT (N'') NULL,
    [calendar]          INT              CONSTRAINT [DF_mc_groups_calendar] DEFAULT ('0') NULL,
    [doclibrary]        INT              CONSTRAINT [DF_mc_groups_doclibrary] DEFAULT ('0') NULL,
    [password]          NVARCHAR (20)    CONSTRAINT [DF_mc_groups_password] DEFAULT (N'') NULL,
    [private]           BIT              CONSTRAINT [DF_mc_groups_private] DEFAULT ((0)) NULL,
    [type_id]           INT              CONSTRAINT [DF_mc_groups_type_id] DEFAULT ('0') NULL,
    [createdBy]         INT              CONSTRAINT [DF_mc_groups_createdBy] DEFAULT ('0') NULL,
    [createdOn]         DATETIME2 (0)    CONSTRAINT [DF_mc_groups_createdOn] DEFAULT (NULL) NULL,
    [owner]             INT              CONSTRAINT [DF_mc_groups_owner] DEFAULT ('0') NULL,
    [active]            BIT              CONSTRAINT [DF_mc_groups_active] DEFAULT ((0)) NULL,
    [openclose]         BIT              CONSTRAINT [DF_mc_groups_openclose] DEFAULT ((0)) NULL,
    [connectID]         INT              CONSTRAINT [DF_mc_groups_connectID] DEFAULT ('0') NULL,
    [surveys]           BIT              CONSTRAINT [DF_mc_groups_surveys] DEFAULT ((0)) NOT NULL,
    [wiki]              INT              CONSTRAINT [DF_mc_groups_wiki] DEFAULT ('0') NOT NULL,
    [polls]             BIT              CONSTRAINT [DF_mc_groups_polls] DEFAULT ((0)) NOT NULL,
    [newsletters]       INT              CONSTRAINT [DF_mc_groups_newsletters] DEFAULT ('0') NOT NULL,
    [homepage]          INT              CONSTRAINT [DF_mc_groups_homepage] DEFAULT ('0') NOT NULL,
    [photos]            BIT              CONSTRAINT [DF_mc_groups_photos] DEFAULT ((0)) NOT NULL,
    [terms]             BIT              CONSTRAINT [DF_mc_groups_terms] DEFAULT ((0)) NOT NULL,
    [notes]             NVARCHAR (MAX)   NULL,
    [allowemails]       BIT              CONSTRAINT [DF_mc_groups_allowemails] DEFAULT ((1)) NOT NULL,
    [swelcomemessage]   NVARCHAR (MAX)   NULL,
    [allowcustom]       BIT              CONSTRAINT [DF_mc_groups_allowcustom] DEFAULT ((0)) NOT NULL,
    [allownotes]        BIT              CONSTRAINT [DF_mc_groups_allownotes] DEFAULT ((1)) NOT NULL,
    [allowcustommember] BIT              CONSTRAINT [DF_mc_groups_allowcustommember] DEFAULT ((0)) NOT NULL,
    [sMemberMessage]    NVARCHAR (MAX)   NULL,
    [group_shortname]   NVARCHAR (255)   CONSTRAINT [DF_mc_groups_group_shortname] DEFAULT (NULL) NULL,
    [homepagecontent]   NVARCHAR (MAX)   NULL,
    [sPopPage]          BIT              CONSTRAINT [DF_mc_groups_sPopPage] DEFAULT ((0)) NOT NULL,
    [bAllowPending]     BIT              CONSTRAINT [DF_mc_groups_bAllowPending] DEFAULT ((0)) NOT NULL,
    [isystem_id]        INT              CONSTRAINT [DF_mc_groups_isystem_id] DEFAULT ('0') NOT NULL,
    [kb_id]             INT              CONSTRAINT [DF_mc_groups_kb_id] DEFAULT ('0') NOT NULL,
    [link_id]           INT              CONSTRAINT [DF_mc_groups_link_id] DEFAULT ('0') NOT NULL,
    [daccess_start]     DATETIME2 (0)    CONSTRAINT [DF_mc_groups_daccess_start] DEFAULT (NULL) NULL,
    [daccess_end]       DATETIME2 (0)    CONSTRAINT [DF_mc_groups_daccess_end] DEFAULT (NULL) NULL,
    [twitter_id]        NVARCHAR (50)    CONSTRAINT [DF_mc_groups_twitter_id] DEFAULT (NULL) NULL,
    [rss]               BIT              CONSTRAINT [DF_mc_groups_rss] DEFAULT ((0)) NOT NULL,
    [video]             BIT              CONSTRAINT [DF_mc_groups_video] DEFAULT ((0)) NOT NULL,
    [logo]              NVARCHAR (200)   CONSTRAINT [DF_mc_groups_logo] DEFAULT (NULL) NULL,
    [sponsor_name]      NVARCHAR (200)   CONSTRAINT [DF_mc_groups_sponsor_name] DEFAULT (NULL) NULL,
    [merged_group_id]   INT              CONSTRAINT [DF_mc_groups_merged_group_id] DEFAULT ('0') NOT NULL,
    [ssubjectprefix]    NVARCHAR (50)    CONSTRAINT [DF_mc_groups_ssubjectprefix] DEFAULT (NULL) NULL,
    [publichomepage]    INT              CONSTRAINT [DF_mc_groups_publichomepage] DEFAULT ('0') NOT NULL,
    [internalnews]      BIT              CONSTRAINT [DF_mc_groups_internalnews] DEFAULT ((1)) NOT NULL,
    [stwitteruser]      NVARCHAR (50)    CONSTRAINT [DF_mc_groups_stwitteruser] DEFAULT (NULL) NULL,
    [stwitterpass]      NVARCHAR (50)    CONSTRAINT [DF_mc_groups_stwitterpass] DEFAULT (NULL) NULL,
    [bdisableaccess]    BIT              CONSTRAINT [DF_mc_groups_bdisableaccess] DEFAULT ((0)) NOT NULL,
    [bfromgroupname]    BIT              CONSTRAINT [DF_mc_groups_bfromgroupname] DEFAULT ((1)) NOT NULL,
    [blogoinemail]      BIT              CONSTRAINT [DF_mc_groups_blogoinemail] DEFAULT ((0)) NULL,
    [formXReportsID]    UNIQUEIDENTIFIER NULL,
    [useProjectTracker] BIT              CONSTRAINT [DF_mc_groups_useProjectTracker] DEFAULT ((0)) NULL,
    [brandingEnabled]   BIT              CONSTRAINT [DF_mc_groups_brandingEnabled] DEFAULT ((0)) NOT NULL,
    [SendWelcomeEmail]  BIT              CONSTRAINT [DF_mc_groups_SendWelcomeEmail] DEFAULT ((0)) NOT NULL,
    [WelcomeEmailSent]  DATETIME2 (7)    NULL,
    [sort]              INT              DEFAULT ((0)) NOT NULL,
    [IsDemo]            BIT              CONSTRAINT [DF_mc_groups_IsDemo] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_mc_groups] PRIMARY KEY CLUSTERED ([Group_ID] ASC)
);




GO
CREATE NONCLUSTERED INDEX [IX_mc_groups_group]
    ON [dbo].[mc_groups]([Group_ID] ASC, [Group_Name] ASC);

