ALTER TABLE [dbo].[meetingsRoles]
    ADD CONSTRAINT [PK__meetings__3213E83F3530BDEA] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

